import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Navbar, NavbarBrand, NavbarContent, NavbarItem, NextUIProvider} from "@nextui-org/react";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import Link from "next/link";
import React from "react";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "All Ditto Ria",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        >
        <NextUIProvider>
            <NextThemesProvider
                defaultTheme="system"
                attribute="class"
                value={{
                    light: 'light',
                    dark: 'dark'
                }}
            >
                <Navbar>
                    <NavbarBrand>
                        <p className="font-bold text-inherit">All Ditto Ria</p>
                    </NavbarBrand>
                    <NavbarContent className="hidden sm:flex gap-4" justify="center">
                        <NavbarItem>
                            <Link color="foreground" href="/">
                                Questionários
                            </Link>
                        </NavbarItem>
                        <NavbarItem>
                            <Link href="/templates" aria-current="page">
                                Templates
                            </Link>
                        </NavbarItem>
                        <NavbarItem>
                            <Link href="/classifications" aria-current="page">
                                Classificação de NC
                            </Link>
                        </NavbarItem>
                       
                    </NavbarContent>
                </Navbar>
                {children}
            </NextThemesProvider>
        </NextUIProvider>
        </body>
        </html>
    )
        ;
}
